// Code generated by "stringer -linecomment -type BuildStatus"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BuildNotStarted-0]
	_ = x[BuildInProgress-1]
	_ = x[BuildFinished-2]
	_ = x[BuildFailed-3]
}

const _BuildStatus_name = "Not startedIn progressFinishedFailed"

var _BuildStatus_index = [...]uint8{0, 11, 22, 30, 36}

func (i BuildStatus) String() string {
	if i < 0 || i >= BuildStatus(len(_BuildStatus_index)-1) {
		return "BuildStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BuildStatus_name[_BuildStatus_index[i]:_BuildStatus_index[i+1]]
}
